# Generated by Django 6.0.2 on 2026-02-19 22:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "time_of_day",
                    models.CharField(
                        choices=[("morning", "Mañana"), ("night", "Noche")],
                        max_length=10,
                        verbose_name="Momento del día",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("intense", "Medición Intensa"),
                            ("control", "Medición de Control"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de medición",
                    ),
                ),
                (
                    "supplements",
                    models.TextField(
                        blank=True, verbose_name="Suplementos y Vitaminas"
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("happy", "Feliz"),
                            ("neutral", "Normal"),
                            ("stressed", "Estresado"),
                            ("sad", "Triste"),
                            ("tired", "Cansado"),
                        ],
                        max_length=50,
                        verbose_name="Estado de ánimo",
                    ),
                ),
                (
                    "food_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo de comida"
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Actividad física"
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "avg_systolic",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Media Sistólica"
                    ),
                ),
                (
                    "avg_diastolic",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Media Diastólica"
                    ),
                ),
                (
                    "avg_pulse",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Media Pulsaciones"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeasurementReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("systolic", models.PositiveIntegerField(verbose_name="Sistólica")),
                ("diastolic", models.PositiveIntegerField(verbose_name="Diastólica")),
                ("pulse", models.PositiveIntegerField(verbose_name="Pulsaciones")),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="tracking.measurementsession",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
